baseURL = 'https://example.org/'
languageCode = 'zh-CN'
title = 'Lucid 主题演示'


# 网站参数
[params]
  # 基本信息
  author = "Lucid"
  description = "Lucid "
  favicon = "/images/favicon.png"  
  
  # 个人资料配置
  [params.profile]
    name = "username"
    bio = "bio"
    avatar = "/images/avatar.png"  # 头像图片路径，相对于 static 目录
  
  # 社交媒体链接
  [params.social]
    email = "x"
    github = "https://github.com/looechao"
    rss = ""

  # Gitalk 评论配置
  [params.gitalk]
    enable = true
    clientID = "4fad9f9325f73f2c2891"
    clientSecret = "109ed02ced3608e776a41f87de4ef9986f5b5fd6"
    repo = "hugo-comments"
    owner = "looechao"
    admin = ["looechao"]
    labels = ["gitalk"]
    perPage = 50
    pagerDirection = "last"
    createIssueManually = false
    distractionFreeMode = false
    language = "zh-CN"


[menus]
  [[menus.main]]
    name = '首页'
    pageRef = '/'
    weight = 10

  [[menus.main]]
    name = '文章'
    pageRef = '/posts'
    weight = 20

  [[menus.main]]
    name = '标签'
    pageRef = '/tags'
    weight = 30

  [[menus.main]]
    name = '归档'
    url = '/archive/'
    weight = 40

[module]
  [module.hugoVersion]
    extended = false
    min = '0.146.0'
